import { Layout, Table } from "antd";
import { AnyObject } from "antd/es/_util/type";
import { ColumnsType } from "antd/es/table";
import Head from "next/head";
import { useEffect, useState } from "react";
import MainHeader from "~/components/header/mainheader";
const { Content } = Layout;
import { api } from "~/utils/api";
import { v4 as uuid } from 'uuid';

export default function Home() {
  const getData = api.object.getObjects.useQuery();
  const [tableData, setTableData] = useState<AnyObject[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  const setData = () => {
    if (!getData.isLoading) {
      setLoading(false)
    }
    if (getData.data) {
      setTableData([]);

      for (const el of getData.data) {

        const tmp: AnyObject = {
          ...el,
          key: uuid(),


        }

        setTableData(oldArray => [...oldArray, tmp]);

      }

    }


  }

  useEffect(() => {
    setData();

  }, [getData.data]);

  const columns: ColumnsType<AnyObject> = [
    {
      title: 'id',
      dataIndex: 'id',
      key: 'id',

    },
    {
      title: 'Название',
      dataIndex: 'name',
      key: 'name',

    },
    {
      title: 'Адрес',
      dataIndex: 'address',
      key: 'address',

    },
    {
      title: 'Описание',
      dataIndex: 'description',
      key: 'description',

    },


  ];
  return (
    <>
      <Head>
        <title>База данных</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center">
        <Layout className="h-full w-full pl-2 pr-2  rounded-md block-bg text-slate">
          <MainHeader />
          <Content className="mt-2 h-max inline-block content">
          <h1 className="text-center">Таблица объектов</h1>
            <Table
              bordered
              className="mt-1"
              columns={columns}
              dataSource={tableData}
              loading={loading}
            >
            </Table>
          </Content>
        </Layout>
      </main>
    </>
  );
}

