import { Layout, Table } from "antd";
import { AnyObject } from "antd/es/_util/type";
import { ColumnsType } from "antd/es/table";
import Head from "next/head";
import { useEffect, useState } from "react";
import MainHeader from "~/components/header/mainheader";
const { Content } = Layout;
import { api } from "~/utils/api";
import { v4 as uuid } from 'uuid';
import moment from "moment";

export default function Security() {
    const getData = api.security.getSecurity.useQuery();
    const [tableData, setTableData] = useState<AnyObject[]>([]);
    const [loading, setLoading] = useState<boolean>(true);

    const setData = () => {
        if (!getData.isLoading) {
            setLoading(false)
        }

        if (getData.data) {
            setTableData([]);

            for (const el of getData.data) {

                const tmp: AnyObject = {
                    ...el,
                    key: uuid(),
                    rank: el.rank.rankName

                }

                setTableData(oldArray => [...oldArray, tmp]);

            }

        }


    }

    useEffect(() => {
        setData();
    }, [getData.data]);

    const columns: ColumnsType<AnyObject> = [
        {
            title: 'id',
            dataIndex: 'id',
            key: 'id',

        },
        {
            title: 'ФИО',
            dataIndex: 'FIO',
            key: 'FIO',

        },
        {
            title: 'Возраст',
            dataIndex: 'age',
            key: 'age',

        },
        {
            title: 'Разряд',
            dataIndex: 'rank',
            key: 'rank',

        },
        {
            title: 'Телефон',
            dataIndex: 'phone',
            key: 'phone',

        },
        {
            title: 'Дата устройства',
            dataIndex: 'employmentDate',
            key: 'employmentDate',
            render: (value:string)=>(moment(value).format("DD.MM.YY")),

        },





    ];
    return (
        <>
            <Head>
                <title>База данных</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" flex min-h-screen flex-col items-center justify-center">
                <Layout className="h-full w-full pl-2 pr-2  rounded-md block-bg text-slate">
                    <MainHeader />
                    <Content className="mt-2 h-max inline-block content">
                    <h1 className="text-center">Таблица охранников</h1>
                        <Table
                            bordered
                            className="mt-1"
                            columns={columns}
                            dataSource={tableData}
                            loading={loading}
                        >
                        </Table>
                    </Content>
                </Layout>
            </main>
        </>
    );
}

